### ISSUE TITLE
Concat the files that shouldn't be a list

### ISSUE THREAD

**Issue by odarbelaeze** [coreofscience/python-wostools#1]
Right now the parser doesn't concat any fields, leaving all as a list, mostly with one element, we should fix that by concating the different lines in the fields that shouldn't be a list.

**Comment by EmPiFree** [comment]
I would like to take this.

**Comment by odarbelaeze** [comment]
@EmPiFree give it a try, here's where the code for that might go https://github.com/coreofscience/python-wostools/blob/master/wostools.py#L44-L61.

**Comment by EmPiFree** [comment]
Is there a possibility to test my code? I would like to experiment a bit, but I don't wanna PR everytime.

**Comment by odarbelaeze** [comment]
@EmPiFree you're right, this repository doesn't contain example data or docs, let me create a couple issues for that.

**Comment by odarbelaeze** [comment]
There's an example data file in #3

**Comment by EmPiFree** [comment]
@odarbelaeze But how can I use the file now? I can't see any possibility to run the code.

**Comment by odarbelaeze** [comment]
I added an example of how to use the code in the README, the example also highlights what this issue is all about, the `TI` tltle should be a string instead of a list.

**Comment by EmPiFree** [comment]
@odarbelaeze Thanks. But you sure it works with that file? I didn't change anything yet.
I get an error using Python 3.6.5:

```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    for article in collection.articles:
  File "/home/levi/git/python-wostools/wostools/wostools.py", line 110, in articles
    for article_text in self.article_texts:
  File "/home/levi/git/python-wostools/wostools/wostools.py", line 99, in article_texts
    data = filehandle.read()
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 1500: ordinal not in range(128)
```

**Comment by EmPiFree** [comment]
I am getting this:

```
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    print(article.TI)
  File "/home/levi/git/python-wostools/wostools/wostools.py", line 56, in __getattr__
    f'{self.__class__.__name__} does not have an attribute {name}'
AttributeError: Article does not have an attribute TI
```
Is this the issue?

**Comment by EmPiFree** [comment]
I got it fixed now. I think I need permission to push it?

**Comment by odarbelaeze** [comment]
Do you wanna fork the repo and make a pull request? you push your local changes to your fork of the repo and then github offers to create a pull request against mine, if that's too cumbersome I could add you as a collaborator.

**Comment by odarbelaeze** [comment]
Do you wanna fork the repo and make a pull request? you push your local changes to your fork of the repo and then github offers to create a pull request against mine, if that's too cumbersome I could add you as a collaborator.
